In [1]:
import os
print(os.getcwd())

C:\Users\K Shridharan

In [2]:
import os
print(os.listdir())

['.arduinoIDE', '.bash_history', '.codex', '.copilot', '.equo', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jdks', '.jupyter', '.keras', '.knime', '.matplotlib', '.packettracer', '.viminfo', '.VirtualBox', '.vscode', '.vscode-shared', 'ansel', 'AppData', 'Application Data', 'Cisco Packet Tracer 8.2.1', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'evil.c', 'Exp_4_Matrices.c', 'Favorites', 'HTML TURORIAL', 'IdeaProjects', 'knime-workspace', 'knime-workspace1', 'Links', 'Local Settings', 'Microsoft', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TM.blf', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TM.blf.cnpf', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{f1afc1b5-e85b-11ef-b6c8-cac72a2fd65f}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'Oracle', 'PCAppStore', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'train.csv', 'Untitled-1.c', 'Untitled-2.java', 'Untitled-3.js', 'Untitled-4.txt', 'Untitled.ipynb', 'Untitled1.cpp', 'Untitled1.exe', 'Untitled2.cpp', 'Untitled2.exe', 'Videos', 'VirtualBox VMs']

In [3]:
import pandas as pd
#loading the data set 
df = pd.read_csv("train.csv")
#seeing the first 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
# how many rows and columns?
print("Shape:", df.shape)

#Column names, data types, missing values
df.info()

Shape: (9800, 18)
<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [5]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [6]:
df[df['Postal Code'].isnull()]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
2234,2235,CA-2018-104066,05/12/2018,10/12/2018,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10001013,Technology,Accessories,Logitech ClearChat Comfort/USB Headset H390,205.03
5274,5275,CA-2016-162887,07/11/2016,09/11/2016,Second Class,SV-20785,Stewart Visinsky,Consumer,United States,Burlington,Vermont,NaN,East,FUR-CH-10000595,Furniture,Chairs,Safco Contoured Stacking Chairs,715.20
8798,8799,US-2017-150140,06/04/2017,10/04/2017,Standard Class,VM-21685,Valerie Mitchum,Home Office,United States,Burlington,Vermont,NaN,East,TEC-PH-10002555,Technology,Phones,Nortel Meridian M5316 Digital phone,1294.75
9146,9147,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,TEC-AC-10002926,Technology,Accessories,Logitech Wireless Marathon Mouse M705,99.98
9147,9148,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-AR-10003477,Office Supplies,Art,4009 Highlighters,8.04
9148,9149,US-2017-165505,23/01/2017,27/01/2017,Standard Class,CB-12535,Claudia Bergmann,Corporate,United States,Burlington,Vermont,NaN,East,OFF-ST-10001526,Office Supplies,Storage,Iceberg Mobile Mega Data/Printer Cart,1564.29
9386,9387,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10000157,Office Supplies,Paper,Xerox 191,79.92
9387,9388,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-PA-10001970,Office Supplies,Paper,Xerox 1881,12.28
9388,9389,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-AP-10000828,Office Supplies,Appliances,Avanti 4.4 Cu. Ft. Refrigerator,542.94
9389,9390,US-2018-127292,19/01/2018,23/01/2018,Standard Class,RM-19375,Raymond Messe,Consumer,United States,Burlington,Vermont,NaN,East,OFF-EN-10001509,Office Supplies,Envelopes,Poly String Tie Envelopes,2.04
9741,9742,CA-2016-117086,08/11/2016,12/11/2016,Standard Class,QJ-19255,Quincy Jones,Corporate,United States,Burlington,Vermont,NaN,East,FUR-BO-10004834,Furniture,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",4404.90

In [9]:
#Filling missing values
df['Postal Code'] = df['Postal Code'].fillna(5401)

In [10]:
#verifying the work is done or not 
print(df['Postal Code'].isnull().sum())

0

In [12]:
#to convert order date and ship date from text to proper date
df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst = True)
df['Ship Date'] = pd.to_datetime(df['Ship Date'], dayfirst = True)

In [13]:
#verifying the change 
print(df[['Order Date', 'Ship Date']].dtypes)

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [18]:
df['Shipping Days'] = (df['Ship Date'] - df['Order Date']).dt.days
df[['Order Date', 'Ship Date', 'Shipping Days']].head(200)

    Order Date  Ship Date  Shipping Days
0   2017-11-08 2017-11-11              3
1   2017-11-08 2017-11-11              3
2   2017-06-12 2017-06-16              4
3   2016-10-11 2016-10-18              7
4   2016-10-11 2016-10-18              7
..         ...        ...            ...
195 2015-03-21 2015-03-25              4
196 2015-03-21 2015-03-25              4
197 2018-11-06 2018-11-13              7
198 2018-07-06 2018-07-13              7
199 2018-07-06 2018-07-13              7

[200 rows x 3 columns]

In [19]:
pd.set_option('display.max_rows', 60)

In [20]:
#droping unnecessary columns
df = df.drop(columns = ['Row ID'])

In [21]:
#verifying the work is done or not 
print(df.columns.tolist())

['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Shipping Days']

In [22]:
#Saving the cleaned dataset as a new file
df.to_csv("train_cleaned.csv", index = False)

print("File Saved Successfully")

File Saved Successfully